---
name: Deploy main

on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  deploy-main:
    name: Deploy main
    runs-on: ubuntu-latest
    steps:
      - name: Deploy main
        run: echo Deploy main